#Settings File for 
# AirMSPI over smoke
#All Channels except IR Channel

input:
    driver: sdata
    file:  "/home/cdeleon/ULTRASIP/AirMSPI_FIREXAQ/Retrievals/July2923/R5-MerdFWD.sdat"
  
output:
    segment:
        function: [classic, classic] # classic, classic_plot, csv, none
        stream: ["Merd_R5_FWD.txt", screen] # screen, "filename"
    
retrieval:     
    general:
        path_to_internal_files: "/home/cdeleon/grasp/src/retrieval/internal_files/" 

    mode: forward
    
    inversion:
        regime: single_pixel

        convergence:
            minimization_convention: logarithm
            threshold_for_stopping: 1.0e-4
            maximum_iterations_for_stopping: 35
            maximum_iterations_of_Levenberg-Marquardt: 25 
            threshold_for_stopping_Q_iterations: 1e-12
            scale_for_finite_difference: 1.0e-3 #1.0e-2
            normal_system_solver: sparse_matrix_solver
            shift_for_applying_logarithm_to_negative_values: 1.1 
                
        measurement_fitting:
            polarization: relative_polarization_components   
            
        noises:
            noise[1]:
                standard_deviation_synthetic: 0.0
                error_type:  relative
                standard_deviation:  0.010
                measurement_type[1]:
                    type: I
                    index_of_wavelength_involved: [ 1, 2, 3, 4, 5, 6, 7]
            noise[2]:
                standard_deviation_synthetic: 0.0
                error_type:  absolute
                standard_deviation:  0.005
                measurement_type[1]:
                    type: Q
                    index_of_wavelength_involved: [  1, 2, 3, 4, 5, 6, 7]
                measurement_type[2]:
                    type: U
                    index_of_wavelength_involved: [ 1, 2, 3, 4, 5, 6, 7 ]

            noise[3]:
                standard_deviation_synthetic: 0.0
                error_type:  relative
                standard_deviation:  0.020
                measurement_type[1]:
                    type: AOD
                    index_of_wavelength_involved: [ 1, 2, 3, 4, 5, 6, 7]
                    
    forward_model:
        phase_matrix:
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 4
            kernels_folder: "kernels_AirMSPI_5bin_7wl_35ang/"
            radius:
                mode[1]:
                    bins: [ 0.1,  0.1732, 0.3,  1.,  2.9 ]   

                    
        radiative_transfer:
            number_of_layers: 50
            aerosol_profile_vertical_type:    exponential
            molecular_profile_vertical_type: standard_atmosphere
            reference_plane_for_polarization: meridian   
            simulating_observation:
                order_of_scattering: multiple_scattering
                number_of_gaussian_quadratures_for_expansion_coefficients:  41 
                number_of_guassian_quadratures_for_fourier_expansion_coefficients:  20 
                number_of_fourier_expansion_coefficients:  20 
            simulating_derivatives:
                order_of_scattering: single_scattering
                number_of_gaussian_quadratures_for_expansion_coefficients:  21
                number_of_guassian_quadratures_for_fourier_expansion_coefficients:   10
                number_of_fourier_expansion_coefficients:   10     
                    
    products:  
        configuration:
            wavelength_indices_for_angstrom: [1, 2]
        aerosol:
            chemistry: false
            lidar: false                             
            optical_properties: true                
            phase_matrix: false                      
            refractive_index: true                 
            theoretical_bimodal_extinction: false    
            theoretical_bimodal_parameters: false       
        error_estimation:
            aerosol:
                lidar: false           
                optical_properties: false
            parameters: false               
        forcing:
            broadband_flux: false                    
            forcing: false                           
        retrieval:
            fitting: true                        
            parameters: true                      
            residual: true                        
        surface: 
            main_characteristics: true 

    debug:
        additional_information: false
        verbose: true

    constraints:
        characteristic[1]:
            type: size_distribution_precalculated_lognormal
            retrieved: true
            mode[1]: 
                initial_guess:                      #1        #2        #3        #4        #5 
                    value:                          [0.01,     0.01,     0.01,     0.01,     0.01      ]
                    min:                            [0.000005, 0.000005, 0.000005, 0.000005, 0.000005  ]
                    max:                            [5.0,      5.0,      5.0,      5.0,      5.0       ]
                    index_of_wavelength_involved:   [0,        0,        0,        0,        0         ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 5.0e-3
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 5.0e-4                                                                  

        characteristic[2]: #6
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:             #1          
                    value:                 [2000.0 ]
                    min:                   [10.0   ] 
                    max:                   [5000.0 ]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 0.0                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 0.0                     
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 0.0               
                                               
                        
        characteristic[3]: #7
            type: surface_land_brdf_ross_li
            retrieved: true
            mode[1]:    
                initial_guess:                       #1     #2     #3
                    value:                          [^repeat(0.1;7)   ]     
                    min:                            [^repeat(0.001;7)]
                    max:                            [0.2, 0.2,  0.2,   0.3,  0.4,   0.7,   0.8]
                    index_of_wavelength_involved:   [^expand(1;7)]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.0e-4
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0                            

            mode[2]:
                initial_guess:                       #1     #2     #3
                    value:                          [0.1  ]    
                    min:                            [0.01 ]
                    max:                            [2.0  ]
                    index_of_wavelength_involved:   [0    ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0e-0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0

            mode[3]:
                initial_guess:                       #1     #2     #3       
                    value:                          [0.1 ]
                    min:                            [0.01]
                    max:                            [1.0 ]
                    index_of_wavelength_involved:   [0   ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0e-0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0                            

        characteristic[4]: #8
            type: surface_land_polarized_maignan_breon
            retrieved: true
            mode[1]:
                initial_guess:                       #1        #2        #3         
                    value:                          [2.1  ]
                    min:                            [0.01 ]
                    max:                            [10.03 ]
                    index_of_wavelength_involved:   [0]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0e-0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 0.0e-3                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 0.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0  

        characteristic[5]: #2
            type: real_part_of_refractive_index_spectral_dependent
            retrieved: false
            mode[1]:
                initial_guess:                      #1         #2        #3
                    value:                         [1.39923 ]
                    min:                           [1.00]
                    max:                           [1.8 ]
                    index_of_wavelength_involved:  [0 ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.0e-1
                multi_pixel:
                    smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 0.0                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 0.0                     
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 0.0                    
                                                     
        characteristic[6]: #3
            type: imaginary_part_of_refractive_index_spectral_dependent
            retrieved: false
            mode[1]:
                initial_guess:                       #1         #2        #3 
                    value:                          [0.0050372,0.0050385,0.0050427,0.0050443,0.0050421,0.0050595,0.0050304   ]
                    min:                            [^repeat(0.00005;7)   ]
                    max:                            [^repeat(0.1;7)       ]
                    index_of_wavelength_involved:   [^expand(1;7)         ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 1.0e-1
                multi_pixel:
                    smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 0.0                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 0.0                     
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 0.0                    
 
        characteristic[7]: #4
            type: sphere_fraction
            retrieved: false
            mode[1]:
                initial_guess:                       #1      
                    value:                          [0.29651]
                    min:                            [0.00001]
                    max:                            [0.9999]
                    index_of_wavelength_involved:   [0]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
                multi_pixel:
                    smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 0.0                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 0.0                     
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 0.0  

